### ISSUE TITLE
Ревью вашего кода

### ISSUE THREAD

**Issue by iHelos** [Evgeny-Ivanov/frontend#2]
Вроде неплохо (правда я Backend'ер, так что :smile: )
Единственное, думаю стоит добавить соединение css'ок в одну большую, чтобы не подгружать много разных.
Для этого есть grunt-concat-css
https://www.npmjs.com/package/grunt-concat-css

+ Можете глянуть как это используется например здесь:
https://github.com/iHelos/Frontend/blob/master/Gruntfile.js

**Comment by Evgeny-Ivanov** [comment]
Мы все-таки исправили
